export const GET_ALL_USERS = 'GET_ALL_USERS';
export const SET_EMAIL_USER_DETAIL = 'SET_EMAIL_USER_DETAIL';
export const DELETE_USER = 'DELETE_USER';
export const SWITCH_USER_ACTIF = 'SWITCH_USER_ACTIF';
export const POST_NEW_USER = 'POST_NEW_USER';
export const SET_PAGINATE_NUMBER = 'SET_PAGINATE_NUMBER';
export const SET_DATA_USER_IN_EDIT = 'SET_DATA_USER_IN_EDIT';
export const PUT_USER = 'PUT_USER';